
on:
  push:
    branches: 
      - master




jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME2 }} --password ${{ secrets.DOCKER_TOKEN2 }}

      - name: "Build Docker image1"
        run: docker build -t ${{ secrets.DOCKER_USERNAME2 }}/myimage1  .

      - name: "Pushing Docker image1"
        run: docker push ${{ secrets.DOCKER_USERNAME2 }}/myimage1  


